#!/bin/bash

# Test H.264 snapshot and recording functionality
echo "=== Testing H.264 Snapshot & Recording ==="

echo ""
echo "Commands to run:"
echo ""
echo "1. Build:"
echo "   cd build && cmake .. && make"
echo ""
echo "2. Run server with H.264:"
echo "   ./v4l2rtspserver -fH264 -W 640 -H 360 -F 30 -j /tmp/test_h264.mp4 -O /tmp/test_O.mp4 /dev/video0 -vv"
echo ""
echo "3. In another terminal, test HTTP snapshot:"
echo "   curl -o /tmp/snapshot_h264.mp4 http://localhost:8554/snapshot"
echo ""
echo "4. Stop server after 5-10 seconds (Ctrl+C)"
echo ""
echo "5. Check files:"
echo "   file /tmp/test_h264.mp4 /tmp/test_O.mp4 /tmp/snapshot_h264.mp4"
echo "   ffprobe /tmp/test_h264.mp4"
echo "   ffprobe /tmp/test_O.mp4"
echo "   ffprobe /tmp/snapshot_h264.mp4"
echo "   mp4box -info /tmp/test_h264.mp4"
echo "   mp4box -info /tmp/test_O.mp4"
echo ""
echo "6. Play files:"
echo "   vlc /tmp/test_h264.mp4"
echo "   vlc /tmp/test_O.mp4"
echo "   vlc /tmp/snapshot_h264.mp4"
echo ""
echo "Expected results:"
echo "   - /tmp/test_h264.mp4: single-frame MP4 snapshot (from -j parameter)"
echo "   - /tmp/test_O.mp4: multi-frame MP4 recording (from -O parameter)"
echo "   - /tmp/snapshot_h264.mp4: single-frame MP4 snapshot (from HTTP /snapshot)"
echo "   - All files should play correctly in VLC/QuickTime"
echo "   - ffprobe should show valid H.264 streams"
echo "   - mp4box should report valid MP4 structure"
echo ""
