name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        buildtype: [Debug, Release]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    
    - name: build
      run: | 
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} .
          make

    - name: cpack
      run: | 
          cpack
          echo "artifactPath=$(ls *.deb)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: ${{ env.artifactPath }}
        path: ${{ env.artifactPath }}    

    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.artifactPath }}
