name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        buildtype: [Debug, Release]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: build
      run: | 
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} .
          make

    - name: cpack
      run: | 
          cpack
          echo "artifactPath=$(ls *.deb)" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.artifactPath }}
        path: ${{ env.artifactPath }}    

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.artifactPath }}
